Preparations for deploy
UladKonop/test-guru pull request #17
Opened 2022-02-06 12:59 UTC by UladKonop

2022-02-07 06:56 UTC, BubuntuClu requested changes

2022-02-07 06:56 UTC, BubuntuClu commented on app/controllers/admin/questions_controller.rb
> +      redirect_to new_admin_test_question_path(@test), alert: 'Question was not created.'
нет, должна открыться страница вопроса с отображением ошибок валидации. твой вариант не подходит

2022-02-07 06:56 UTC, BubuntuClu commented on app/controllers/user_tests_controller.rb
> +    redirect_to session.delete(:return_to), alert: 'No questions present.' unless @user_test.question
вот добавиться 1 вопрос в тест, а ответов еще нет, но тест уже можно будет проходить. зайдешь в такой тест, а не можешь его проходить, так как будешь натыкаться на ошибку `'Select at least one question'`. надо придумать что-то более логичное чем проверка наличия вопросов

2022-02-07 06:56 UTC, BubuntuClu commented on app/controllers/user_tests_controller.rb
> +    redirect_to session.delete(:return_to), alert: 'No questions present.' unless @user_test.question
ну и скорее всего это должно происходить на `tests#index`

2022-02-07 07:00 UTC, BubuntuClu commented on app/controllers/user_tests_controller.rb
> +    redirect_to session.delete(:return_to), alert: 'No questions present.' unless @user_test.question
да и странно выглядит текущая ситуация, видишь тест, а пройти его не можешь. зачем его тогда показывать?

2022-02-12 18:23 UTC, BubuntuClu requested changes

2022-02-12 18:23 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @tests = Test.joins(:questions).group('id')
ты придумываешь костыли. добавил ты вопрос в тест, он стал показываться, но ответов у вопроса нет. тест не готов к отображению.

просто сделай флаг, который будет отвечать за то, готов ли тест к публикации/к прохождению

2022-02-13 18:33 UTC, BubuntuClu requested changes

2022-02-13 18:33 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +      @answer.question.test.update!(ready_to_start: true)
почему бэнг метод используешь? обработчик не написал на случай падения

2022-02-13 18:33 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +  after_action :check_answers_amount, only: :destroy
почему удаление ответов влияет на флаг?

2022-02-13 18:33 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +    @answer.question.test.update!(ready_to_start: false) if @answer.question.answers.count.zero?
бэнг метод без обработчика

2022-02-13 18:33 UTC, BubuntuClu commented on app/controllers/admin/questions_controller.rb
> +    @question.test.update!(ready_to_start: false) if @question.test.questions.count.zero?
бэнг метод

2022-02-13 18:33 UTC, BubuntuClu commented on db/migrate/20210915184818_create_tests.rb
> +      t.boolean :ready_to_start, default: false
нельзя править смерженные миграции. надо вносить правки в существующие таблицы только через новые миграции. откати этот код и добавь новую миграцию на создание этого поля

2022-02-13 18:40 UTC, UladKonop commented on app/controllers/admin/answers_controller.rb
> +  after_action :check_answers_amount, only: :destroy
ну если не будет ответов у вопроса, то как проходить тест? вопросы добавлены, а ответы ещё нет. или наоборот сокращение числа ответов на вопрос до нуля

2022-02-14 06:59 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +  after_action :check_answers_amount, only: :destroy
модератор сам следит за флагом и если что-то удаляет, то перед этим переводит тест в неопубликованный? как такой вариант

2022-02-14 08:21 UTC, merged